apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "webserver.fullname" . }}
  labels:
    {{- include "webserver.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "webserver.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None

