---
# Containers are under development
containers:
  - name: gitea
    image: gitea/gitea:1.16.8-rootless
    ports:
      - name: gitea
        containerPort: 3000
        protocol: TCP
    environment:
      GITEA__DEFAULT__RUN_MODE: dev
      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db
      GITEA__picture__DISABLE_GRAVATAR: "true"
      GITEA__repository__DEFAULT_PRIVATE: "false"
      GITEA__repository__DEFAULT_PUSH_CREATE_PRIVATE: "false"
      GITEA__repository__ENABLE_PUSH_CREATE_ORG: "true"
      GITEA__repository__ENABLE_PUSH_CREATE_USER: "true"
      GITEA__repository__ONLY_ALLOW_PUSH_IF_GITEA_ENVIRONMENT_SET: "false"
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__server__SSH_DOMAIN: http://gitea
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__service__REQUIRE_SIGNIN_VIEW: "false"
      GITEA__webhook__ALLOWED_HOST_LIST: '*'
    volumeMounts:
      - name: gitea-varlib
        mountPath: /var/lib/gitea/
      - name: gitea-data
        mountPath: /data/
      - name: gitea-etc
        mountPath: /etc/gitea
    volumes:
      - name: gitea-data
        emptyDir: {}
      - name: gitea-etc
        emptyDir: {}
      - name: gitea-varlib
        emptyDir: {}
    commands: 
        - gitea admin user create --admin --username gitea --password gitea --email dummy@dummy.com --must-change-password=false
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea' 
          -d '{"username": "student", "full_name": "student", "description": "student"}'
          http://localhost:3000/api/v1/orgs
        - >
          curl -X POST -H "accept: application/json" -H "Content-Type: application/json"
          -u 'gitea:gitea'
          -d '{"clone_addr": "https://github.com/nmartins0611/aap25-roadshow-content.git", "repo_name": "aap25-roadshow-content", "owner": "student", "uid": 2, "private": false}'
          http://localhost:3000/api/v1/repos/migrate
    memory: 2Gi
    services:
      - name: gitea
        ports:
          - port: 3000
            protocol: TCP
            targetPort: 3000
            name: gitea
    routes:
      - name: gitea
        host: gitea
        service: gitea
        targetPort: 3000
        tls: true
        tls_termination: Edge
virtualmachines:
  - name: "control"
    image: "aap-25-c-20250611"
    memory: "16G"
    cores: 4
    image_size: "30Gi"
    disk_type: "scsi"
    bootloader: "efi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: control-https
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
            name: control-https
    routes:
      - name: control-https
        host: control
        service: control-https
        targetPort: 443
        tls: true
        tls_termination: reencrypt
        tls_destinationCACertificate: |
          -----BEGIN CERTIFICATE-----
          MIIF1jCCA76gAwIBAgIUbcSVQmlmSv5sq18JRM6RbFCoxukwDQYJKoZIhvcNAQEL
          BQAwgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEQMA4G
          A1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVkIEhhdDEQMA4GA1UECwwHQW5zaWJs
          ZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0aW9uIFBsYXRmb3JtMB4XDTI0MTAz
          MTE3NDcxOVoXDTM0MTAyOTE3NDcxOVowgYIxCzAJBgNVBAYTAlVTMRcwFQYDVQQI
          DA5Ob3J0aCBDYXJvbGluYTEQMA4GA1UEBwwHUmFsZWlnaDEQMA4GA1UECgwHUmVk
          IEhhdDEQMA4GA1UECwwHQW5zaWJsZTEkMCIGA1UEAwwbQW5zaWJsZSBBdXRvbWF0
          aW9uIFBsYXRmb3JtMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqGPt
          nTmsfpjQrd8oMeITRu7hQlCyWPUApwQ2AH7J4gNbvhDLEu/xGFIsh+L2SIAKZ7Ez
          7y1iji6ZMl4uBujhWSK3Luk18BTn9SWxYp+63SninjEUA56yn+bd7/+jwWzSWX2q
          ITIYo8tkZQ9HguFlGR+QUEElO914kxenyjFk+6bW22dTSiDCKEKG6Dl4Tqi7hftx
          RJhn0vpgJH7ULD2EbarsIndtfk3joyZX7s6otuu6XSj0HSo0fEaLf/8eNP1pXho8
          eFnQgC/EWWbmJ9AqHnziO/PpENNl1nRrkqk6O4aH9yDaT4dm6NUONU0ChN4QOSZa
          Pyh2lxwfGt70FuwPT7pygsevLaF8YuJoOLvA2CotEif3q60uK23UsN0y4kXA/tV1
          sV/XPaUWIcVVZtq8rqa6iyswtd9P/UrdbyQ6z18TZxoM1kZIlNb9+JpIQ+UeQfMu
          ZTcyjCTwqoLidwi8czxk1LjMSmjPOP0wDNW9v7mSKwTJl0YEUgBwBSTOjP0Ppy1s
          QozvNmBeRk2NHMWbvL9dO5bCi7dBF2ThQyLpXNK07wcYid3kbEn15C7YVgHYMsys
          qA3nCSY71eS2hSMMYZOsxrSwuDTtWanAxI7XC6rYzmnMUQ8BwgZJGf6D8YWPPYZG
          9hNmkQg9gxAdvZyZgbveiozmA8Y0xgQzqYgNuLECAwEAAaNCMEAwDgYDVR0PAQH/
          BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFI1jIEvL1NZPi4CUz7eu
          o81IadMMMA0GCSqGSIb3DQEBCwUAA4ICAQBH+aHL7Ilj6tuBXnqrzd0YkT9dTRH5
          5kqn1TLrG6RMGEsKLqRiBPwrgvL0TZFhKK1CjrHV1jtmA6HfozHpwcc94vp1znyA
          fcFvvfLH3SUM9b8u+u/fS8sHci1adcxgNghV6vbo3kwH3GFFHauFUP2jyqXE1Dsr
          pMAHbzx0s6B0s5IZ6C2RqvPjEf5UYdmm7g14IO+XWbOnF5WW/WcNR+kyu42EZ7nD
          AyZ7ETfEVczHBC0nvxlEzp5hePd2mWkr+qW22E7nZsIyYF3Pha98MzJMZIxW0Rtk
          NKSdrKUW3Q6Lf8zrHoDwYqqR6Q8fbDgh2mUmUtKcMrgftKoZ9n4he02WnVYmzfcz
          RulRWJ4mV4asbQhzoXhIiDXCIFAHwxTgcJFBobEO/vvExKRchX7ioBNqV9CdhEoL
          7N/Ox96MVw8eFhZQ/l+Umuosx8cd71U/G5tGKZ325wMQcVFgho8fPKjhKvYE8EYK
          McLnqn9Kq1wJRKJil/e2BDlSd1UpD2bH6Qi3AwfiJf/GOJNn1MAjVwpLP4M84M0+
          5IwZ37He14ufo3JD3ef9AJSYYNv4TGf8uxnuovvDgHYu7s+PAhU+QU/aVP9Zz+As
          LoNLIEuIvswEttV5se8BRH1Zim1ZOgMVauejhwOvaqB3pV5u2+DpNoMr+4ERmQNX
          cCq2g7MN0EK+Hw==
          -----END CERTIFICATE-----
  - name: "node01"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }  
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd

  - name: "node02"
    image: "rhel-8.7"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node02-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node02
    routes:
      - name: node02-web
        host: node02
        service: node02-http
        targetPort: 80
        tls: true  ## To resolve https/http Framing
        tls_termination: Edge ## To resolve https/http Framing
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
        - systemctl reload sshd
        
  - name: "node03"
    image: "rhel-9.5"
    memory: "2G"
    cores: 2
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: node03-http
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: node03
    routes:
      - name: node03-web
        host: node03
        service: node03-http
        targetPort: 80
        tls: true
        tls_termination: Edge
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd

  - name: "windows"
    image: "base-zero-windows-2025-3"
    memory: "16G"
    cores: 4
    image_size: "30Gi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    interface_model: "e1000e"
    networks:
      - default
    services:
      - name: windows
        ports:
          - port: 5986
            protocol: TCP
            targetPort: 5986
            name: windows
            
      - name: windows-rdp
        ports:
          - port: 3389
            protocol: TCP
            targetPort: 3389
            name: windows-rdp
      - name: iis
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
            name: iis
    routes:
      - name: windows
        host: windows
        service: iis
        targetPort: 80
        tls: true
        tls_termination: Edge
